# Generated by Django 5.0.3 on 2024-03-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('district', models.CharField(max_length=255, verbose_name='Район')),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
                ('house_number', models.IntegerField(verbose_name='Номер дома')),
                ('type', models.CharField(max_length=255, verbose_name='Тип места проживания')),
                ('rooms_number', models.IntegerField(blank=True, null=True, verbose_name='Кол-во комнат')),
                ('floors_number', models.IntegerField(blank=True, null=True, verbose_name='Кол-во этажей')),
                ('floor_location', models.IntegerField(blank=True, null=True, verbose_name='Этаж расположения')),
                ('area', models.IntegerField(blank=True, null=True, verbose_name='Площадь')),
                ('conditions', models.CharField(max_length=255, verbose_name='Условия')),
                ('bathroom', models.BooleanField(verbose_name='Ванная')),
                ('kitchen', models.BooleanField(verbose_name='Кухня')),
                ('internet', models.BooleanField(verbose_name='Интернет')),
                ('intercom', models.BooleanField(verbose_name='Домофон')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementImage',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='media')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['-created_at'],
            },
        ),
    ]
