# Generated by Django 5.0.3 on 2024-03-31 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementimage',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_images', to='announcements.announcement', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='announcementimage',
            name='image',
            field=models.ImageField(upload_to='media', verbose_name='Фотография объявления'),
        ),
    ]
