# Generated by Django 5.0.3 on 2024-04-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_remove_announcement_intercom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='bathroom',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ванная'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='conditions',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Условия'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=models.TextField(blank=True, max_length=1023, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='kitchen',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кухня'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип места проживания'),
        ),
    ]
