# Generated by Django 5.0.3 on 2024-04-02 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20240331_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('name',), 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='nationality',
            options={'ordering': ('name',), 'verbose_name': 'Национальность', 'verbose_name_plural': 'Национальности'},
        ),
    ]
